import collections.abc
import typing

__all__: collections.abc.Sequence[str] = ("CommandProto", "ConnectionProto")


class CommandProto(typing.Protocol):
    def arg(self, value: str | bytes | int | float) -> "CommandProto": ...

    def __iter__(self) -> typing.Iterator[bytes]: ...

    def __len__(self) -> int: ...


class ConnectionProto(typing.Protocol):
    @classmethod
    async def from_url(cls, url: str, /) -> "ConnectionProto": ...

    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def write_command(self, command: "CommandProto", /) -> None: ...

    async def read_response(self, *, disconnect_on_error: bool) -> typing.Any: ...
